name: Makefile CI

on:
  push:
    branches: [ main, github-workflow ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-10.15, macos-11 ]

    steps:
      - uses: actions/checkout@v3

      - name: Configure
        run: make configure

      - name: Build scc
        run: make all

      - name: Run checks
        run: make tests
